# Generated by Django 5.1.3 on 2025-01-08 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("frequency", models.CharField(max_length=50)),
                ("amount", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
                ("currency", models.CharField(default="PKR", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_incomes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.FloatField()),
                ("currency", models.CharField(default="PKR", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Liability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Loan", "Loan"),
                            ("Credit Card Debt", "Credit Card Debt"),
                            ("Mortgage", "Mortgage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("loan_amount", models.FloatField(blank=True, null=True)),
                ("interest_rate", models.FloatField(blank=True, null=True)),
                ("loan_term", models.CharField(blank=True, max_length=100, null=True)),
                ("monthly_payment", models.FloatField(blank=True, null=True)),
                ("remaining_balance", models.FloatField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("credit_card_balance", models.FloatField(blank=True, null=True)),
                ("credit_card_apr", models.FloatField(blank=True, null=True)),
                ("minimum_payment", models.FloatField(blank=True, null=True)),
                ("credit_limit", models.FloatField(blank=True, null=True)),
                ("revolving_balance", models.FloatField(blank=True, null=True)),
                ("mortgage_amount", models.FloatField(blank=True, null=True)),
                ("mortgage_interest_rate", models.FloatField(blank=True, null=True)),
                (
                    "mortgage_term_length",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mortgage_monthly_payment", models.FloatField(blank=True, null=True)),
                (
                    "mortgage_remaining_balance",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("marital_status", models.CharField(max_length=255)),
                (
                    "number_of_children",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
