# Generated by Django 5.1.3 on 2025-04-05 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCardDebt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("remaining_balance", models.FloatField(blank=True, null=True)),
                ("credit_card_balance", models.FloatField(blank=True, null=True)),
                ("credit_card_apr", models.FloatField(blank=True, null=True)),
                ("minimum_payment", models.FloatField(blank=True, null=True)),
                ("credit_limit", models.FloatField(blank=True, null=True)),
                ("revolving_balance", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("remaining_balance", models.FloatField(blank=True, null=True)),
                ("loan_amount", models.FloatField(blank=True, null=True)),
                ("interest_rate", models.FloatField(blank=True, null=True)),
                ("loan_term", models.CharField(blank=True, max_length=100, null=True)),
                ("monthly_payment", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Mortgage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("remaining_balance", models.FloatField(blank=True, null=True)),
                ("mortgage_amount", models.FloatField(blank=True, null=True)),
                ("mortgage_interest_rate", models.FloatField(blank=True, null=True)),
                (
                    "mortgage_term_length",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mortgage_monthly_payment", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Liability",
        ),
    ]
