# Generated by Django 5.1.3 on 2025-03-20 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="date_saved",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
