# Generated by Django 5.1.3 on 2025-04-05 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_creditcarddebt_loan_mortgage_delete_liability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtTransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liability_type",
                    models.CharField(
                        choices=[
                            ("loan", "Loan"),
                            ("credit_card_debt", "Credit Card Debt"),
                            ("mortgage", "Mortgage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("amount", models.FloatField()),
                ("description", models.CharField(max_length=255)),
                (
                    "credit_card_debt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.creditcarddebt",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.loan",
                    ),
                ),
                (
                    "mortgage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.mortgage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
