# Generated by Django 5.1.3 on 2025-03-21 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_expense_date_saved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "amount_required",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "amount_saved",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("target_date", models.DateField()),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("Short-Term", "Short-Term"),
                            ("Mid-Term", "Mid-Term"),
                            ("Long-Term", "Long-Term"),
                        ],
                        default="Short-Term",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Medium",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
