# Generated by Django 5.1.3 on 2025-04-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_debttransactionhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcarddebt",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mortgage",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
