# Generated by Django 5.1.3 on 2025-03-21 19:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_goal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="target_date",
            new_name="due_date",
        ),
        migrations.RenameField(
            model_name="goal",
            old_name="amount_saved",
            new_name="saved_amount",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="amount_required",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="goal_type",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="priority",
        ),
        migrations.AddField(
            model_name="goal",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
