# Generated by Django 5.1.3 on 2025-04-15 19:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_creditcarddebt_description_loan_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetirementPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_age", models.PositiveIntegerField()),
                ("retirement_age", models.PositiveIntegerField()),
                ("life_expectancy", models.PositiveIntegerField(default=85)),
                (
                    "desired_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("is_annual_income", models.BooleanField(default=True)),
                (
                    "current_savings",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retirement_plan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetirementContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_contributed",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "date_contributed",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retirement_contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retirement_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="api.retirementplan",
                    ),
                ),
            ],
        ),
    ]
