# Generated by Django 5.1.3 on 2025-04-15 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_retirementplan_retirementcontribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaldetails",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
