# Generated by Django 5.1.3 on 2025-04-15 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_personaldetails_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="retirement_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="api.retirementplan",
            ),
        ),
    ]
