# Generated by Django 5.1.3 on 2025-04-19 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_asset_retirement_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="date_saved",
            new_name="date",
        ),
        migrations.AddField(
            model_name="expense",
            name="recurrence_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="subcategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[("fixed", "Fixed"), ("variable", "Variable")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="MonthlyBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveIntegerField()),
                (
                    "budgeted_expense",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "budgeted_emergency_fund",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "budgeted_debt",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "budgeted_retirement",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "budgeted_goal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "spent_expense",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "spent_emergency_fund",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "spent_debt",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "spent_retirement",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "spent_goal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("user", "month", "year")},
            },
        ),
    ]
