# Generated by Django 5.1.3 on 2025-04-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_rename_date_saved_expense_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="recurrence_date",
        ),
        migrations.AddField(
            model_name="expense",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
