# Generated by Django 5.1.3 on 2025-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_expense_recurrence_date_expense_recurrence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="recurrence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
